branches:
  only:
    - master
git:
  depth: 5
stages:
    - name: test
      if: type = pull_request
    - name: deploy
      if: type = push

matrix:
  include:
  -   language: node_js
      node_js:
        - "stable"
      before_install:
        - cd client
      install:
        - npm install
      jobs:
        include:
          - stage: test
            script:
              - npm run lint
          - stage: deploy
            script:
              - CI='' npm run build

  -   language: node_js
      node_js:
        - "stable"
      before_install:
        - cd server
      install:
        - npm install
      jobs:
        include:
          - stage: test
            script: skip
          - stage: deploy
            script: skip