branches:
  only:
    - master
git:
  depth: 5
stages:
    - name: test
      if: type = pull_request
    - name: deploy
      if: type = push

jobs:
  include:
    - stage: test
      matrix:
        include:
          - language: node_js
            node_js:
              - "stable"
            before_install:
              - cd client
            install:
              - npm install
            script:
              - npm run lint
          - language: node_js
            node_js:
              - "stable"
            before_install:
              - cd server
            install:
              - npm install
            script: skip
    - stage: deploy
      matrix:
        include:
          - language: node_js
            node_js:
              - "stable"
            script:
              - cd client ; pwd
          - language: node_js
            node_js:
              - "stable"
            script:
              - cd server ; pwd

#matrix:
#  include:
#  -   language: node_js
#      node_js:
#        - "stable"
#      before_install:
#        - cd client
#      install:
#        - npm install
#      jobs:
#        include:
#          - stage: test
#            script:
#              - npm run lint
#          - stage: deploy
#            script:
#              - CI='' npm run build
#
#  -   language: node_js
#      node_js:
#        - "stable"
#      before_install:
#        - cd server
#      install:
#        - npm install
#      jobs:
#        include:
#          - stage: test
#            script: skip
#          - stage: deploy
#            script: skip