branches:
  only:
    - master
git:
  depth: 5
stages:
    - name: test
      if: type = pull_request
    - name: deploy
      if: type = push

matrix:
  include:
  -   language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      stage: test
      before_install:
        - cd client
      install:
        - npm install
      script:
        - npm run lint

  -   language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      stage: test
      before_install:
        - cd server
      install:
        - npm install

  -   language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      stage: deploy
      before_script:
        - cd client
        - npm install
      script:
        - CI='' npm run build
        - mv build minesweeper2 ; cp ../appspec.yml ./minesweeper2/ ; zip -r minesweeper2 minesweeper2
        - mkdir compressed_build ; mv minesweeper2.zip ./compressed_build/
      deploy:
        - provider: s3
          access_key_id: ${AWS_ACCESS_KEY}
          secret_access_key: ${AWS_SECRET_KEY}
          bucket: ${AWS_DEPLOY_BUCKET}
          skip_cleanup: true
          local_dir: compressed_build
        - provider: codedeploy
          access_key_id: ${AWS_ACCESS_KEY}
          secret_access_key: ${AWS_SECRET_KEY}
          bucket: ${AWS_DEPLOY_BUCKET}
          key: minesweeper2.zip
          bundle_type: zip
          application: minesweeper-deploy
          deployment_group: minesweeper-deployment-group

  -   language: node_js
      node_js:
        - "stable"
      stage: deploy
      before_script:
        - cd server
      script:
        - pwd